"""
Django settings for Opsclick project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6%yd7zq%dc=2e_$w2qa_!-(s%t*m^kr(82ke5=m-j*in2*ve*^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['ec2-35-165-104-169.us-west-2.compute.amazonaws.com']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.redirects",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.stripe',
]
# Internal applications
INSTALLED_APPS += [
    'lostpet_auth',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lostpet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'PAGE_SIZE': 10
}

AUTHENTICATION_BACKENDS = (
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

WSGI_APPLICATION = 'lostpet.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_ROOT = ''
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_URL = '/static/'

ADMIN_NAME = "lostpetuser"
ADMIN_PASSWORD = "lostpetpassword"

BREED = [
"Other","Mutt","Abyssinian","Affenpinscher","Afghan Hound","Airedale Terrier","Akita","Alaskan Malamute","American Bobtail","American Bulldog","American Curl","American Eskimo Dog","American Foxhound","American Shorthair","American Staffordshire Terrier","AMerican Water Spaniel","American Wirehair","Anatolian Shepherd Dog","Angora","Asian Semi-longhair","Asian Shorthair","Australian Cattle Dog","Australian Kelpie","Australian Mist","Australian Shepherd","Australian Terrier","Balinese","Basenji","Basset Hound","Beagle","Bearded Collie","Beauceron","Bedlington Terrier","Belgian Malinois","Belgian Sheepdog","Belgian Tervuren","Bengal cat","Bernese Mountain Dog","Bichon Frise","Birman","Black and Tan Coonhound","Black Mouth Cur","Black Russian Terrier","Bloodhound","Bluetick Coonhound","Bombay","Border Collie","Border Terrier","Borzoi","Boston Terrier","Bouvier Des Flandres","Boxer","Boykin Spaniel","Brazilian Shorthair","Briard","British Shorthair","Brittany","Brussels Griffon","Bull Terrier","Bullmastiff","Burmese","Burmilla","Cairn Terrier","California Spangled Cat","Canaan Dog","Cardigan Welsh Corgi","Catahula Leopard","Cavalier King Charles Spaniel","Chantilly/Tiffany cat","Chartreux","Chausie","Cherubim","Chesapeake Bay Retriever","Chihuahua","Chinese Crested","Chinese SharPei","Chow Chow","Clumber Spaniel","Cocker Spaniel","Collie","Colorpoint Shorthair","Colourpoint Longhair","Cornish Rex","Coton de Tulear","Curly Coated Retriever","Cymric","Dachshund","Dalmation","Dandie Dinmont Terrier","Devon Rex","Doberman Pinscher","Dogue De Bordeaux","Domestic Long Hair","Domestic Short Hair","Don Sphynx","Egyptian Mau","English Bulldog","English Cocker Spaniel","English Foxhound","English Setter","English Springer Spaniel","English Toy Spaniel","European Shorthair","Exotic Shorthair","Field Spaniel","Finnish Spitz","Flat Coated Retriever","French Bulldog","German Pinscher","German Rex","German Shepherd Dog","German Shorthaired Pointer","German Spitz","German Wirehaired Pointer","Giant Schnauzer","Glen of Imall Terrier","Golden Retriever","Gordon Setter","Great Dane","Great Pyrenees","Greater Swiss Mountain Dog","Greyhound","Harrier","Havana Brown","Havanese","Himalayan","Hovawart","Ibizan Hound","Irish Setter","Irish Terrier","Irish Water Spaniel","Irish Wolfhound","Italian Greyhound","Jack Russell Terrier","Japanese Bobtail","Japanese Chin","Javanese","Karelian Bear Dog","Keeshond","Kerry Blue Terrier","Komondor","Korat","Kurilean Bobtail Longhair","Kurilean Bobtail Shorthair","Kuvasz","Labrador Retriever","Lakeland Terrier","LaPerm","Lhasa Apso","Lowchen","Maine Coon","Malayan","Maltese","Manchester Terrier","Manx","Mastiff","Minature Pinscher","Miniature Bull Terrier","Miniature Schnauzer","Mix","Munchkin","Mutt","Neapolitan Mastiff","Nebelung","Newfoundland","Norfolk Terrier","Norwegian Elkhound","Norwegian Forest Cat","Norwich Terrier","Nova Scotia Retriever","Ocicat","Ojos Azules","Old English Sheepdog","Oriental Longhair","Oriental Shorthair","Other","Otterhound","Papillon","Patterdale Terrier","Pekingese","Pembroke Welsh Corgi","Persian","Peterbald","Petit Basset Griffon Vendeen","Pharoah Hound","Pit Bull","Pixie-bob","Plott","Pointer","Polish Lowland Sheepdog","Pomeranian","Poodle","Portuguese Water Dog","Pug","Puggle","Puli","Ragdoll","Rat Terrier","Redbone Coonhound","Rhodesian Ridgeback","Rottweiler","Russian Blue","Saluki","Samoyed","Savannah","Schipperke","Scottish Deerhound","Scottish Fold","Scottish Terrier","Sealyham Terrier","Selkirk Rex","Shetland Sheepdog","Shiba Inu","Shih Tzu","Siamese","Siberian","Siberian Husky","Silky Terrier","Singapura","Skye Terrier","Smooth Fox Terrier","Snowshoe","Soft Coated Wheaten Terrier","Sokoke","Somali","Sphynx","Spinone Italiano","St. Bernard","Staffordshire Bull Terrier","Standard Schnauzer","Sterling","Sussex Spaniel","Tibetan Spaniel","Tibetan Terrier","Tonkinese","Toy Fox Terrier","Toyger","Treeing Walker Coonhound","Turkish Angora","Turkish Van","Vizsla","Weimaraner","Welsh Springer Spaniel","Welsh Terrier","West Highland White Terrier","Whippet","Wire Fox Terrier","Wirehaired Pointing Griffon","York Chocolate","Yorkshire Terrier",
]

# Stripe configuration
STRIPE_PUBLIC_KEY = "pk_test_2lZa1GEBbX36vxn4M7d66skl"
STRIPE_SECRET_KEY = "sk_test_KSlZSYo24FwP7SYsuoOD3zrp"

# Mailchimp configuration
MAILCHIMP_API_KEY = "e19811fcd6b4fb4a2cb6222c85831850-us13"
MAILCHIMP_LIST_ID = "c46ba32300"

# AWS S3 configuration
AWS_ACESS_KEY = "AKIAIX6B5A3U7RBX7YPA"
AWS_SECRET_KEY = "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"

BUCKET = "cuddlesunited"

DIRECTORY = "Lost Pet Flyers"

# smtp configuration
DEFAULT_FROM_EMAIL = 'find@cuddlesunited.com'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'find@cuddlesunited.com'
EMAIL_HOST_PASSWORD = 'lostpets3'

EMIAL_ADMIN = 'processing@cuddlesunited.com'

FACEBOOK_ACCESS_TOKEN = "EAABqlLydN88BAOsvM9mXlpEcFMXM8wTvyAxA \
                   ZCWjetzXs3OntHvNZCK5UlySq4DzbqTTT82GBNDesuhM5Vkyd7YQU9Kgmq2ZCA13qgl9RXJDX3Jgxo2ZC \
                   AOywuMGPmejaZC0PlCYi571AazMrdlgfwDpiZAKy0oVQZD"
FACEBOOK_PAGE_ID = "1524903867818603"

