
HELP_BREED = {
    "dog": {
    "Setter Irish Red and White": "503", 
    "Dachshund": "82", 
    "English Pointer": "93", 
    "Scottish Terrier Scottie": "208", 
    "Eskimo Dog Canadian": "470", 
    "Norwegian Buhund": "167", 
    "Silken Windhound": "514", 
    "Pumi": "193", 
    "Smooth Fox Terrier": "219", 
    "Terrier Soft Coated Wheat": "529", 
    "Basenji": "23", 
    "Belgian Shepherd Malinois": "33", 
    "Black Mouth Cur": "39", 
    "Fox Terrier": "107", 
    "Newfoundlander Landseer": "488", 
    "Canaan Dog": "60", 
    "West Highland White Terrier Westie": "238", 
    "Curly-Coated Retriever": "81", 
    "Beauceron": "29", 
    "Brussels Griffon": "56", 
    "Sheepdog Belgian": "505", 
    "Giant Schnauzer": "117", 
    "Finnish Spitz": "105", 
    "Peruvian Inca Orchid": "177", 
    "Dandi Dinmont Terrier": "84", 
    "Schipperke": "205", 
    "American Bulldog": "12", 
    "Red Heeler": "544", 
    "Yorkie Poo": "540", 
    "Setter": "209", 
    "Irish Setter": "131", 
    "Cocker Spaniel": "76", 
    "Welsh Terrier": "237", 
    "Scottish Deerhound": "207", 
    "Nova Scotia Duck-Tolling Retriever": "170", 
    "Mcnab": "160", 
    "Terrier": "225", 
    "Coton De Tulear": "80", 
    "Fanaraskan": "474", 
    "Others": "447", 
    "Wirehaired Terrier": "244", 
    "Staffordshire Terrier Bull Miniature": "522", 
    "American Eskimo Dog": "13", 
    "English Toy Spaniel": "97", 
    "Havanese": "126", 
    "Labradoodle": "536", 
    "Schnauzer": "206", 
    "Lakeland Terrier": "151", 
    "Clumber Spaniel": "74", 
    "English Cocker Spaniel": "91", 
    "Neapolitan Mastiff": "164", 
    "Silky Terrier": "217", 
    "Manchester Terrier": "157", 
    "Boykin Spaniel": "53", 
    "Podengo Portugueso": "184", 
    "Pharaoh Hound": "179", 
    "Klee Kai": "146", 
    "Swedish Vallhund": "224", 
    "Otterhound": "173", 
    "Welsh Springer Spaniel": "236", 
    "Wire-Haired Pointing Griffon": "243", 
    "Norwegian Elkhound": "168", 
    "Alaskan Husky": "10", 
    "Entlebucher Mountain Dog": "469", 
    "Collie Smooth": "466", 
    "American Water Spaniel": "16", 
    "Lancashire Heeler": "152", 
    "Shih Tzu": "215", 
    "Bolognese": "45", 
    "Greyhound": "124", 
    "Treeing Walker Coonhound": "232", 
    "Yorkshire Terrier Yorkie": "247", 
    "Shepherd Belgian": "511", 
    "Norwich Terrier": "169", 
    "Presa Canario": "190", 
    "Foxhound English": "473", 
    "Chihuahua": "68", 
    "Bluetick Coonhound": "43", 
    "Shiba Inu": "214", 
    "Hound": "127", 
    "Shiloh Shepherd": "457", 
    "Dogo Argentino": "86", 
    "Spaniel Japanese": "519", 
    "Pekingese": "176", 
    "Cattle Dog": "64", 
    "Schnauzer Miniature": "501", 
    "Shepherd Shiloh": "513", 
    "Samoyed": "204", 
    "Cane Corso Mastiff": "61", 
    "Jack Russell Terrier": "137", 
    "Poodle": "188", 
    "Kai Dog": "141", 
    "Entlebucher": "98", 
    "Border Terrier": "48", 
    "Retriever": "196", 
    "Karelian Bear Dog": "142", 
    "Vizsla": "233", 
    "Berger Des Pyrenees": "460", 
    "Puli": "192", 
    "Chinese Crested Dog": "69", 
    "Coonhound": "78", 
    "Great Pyrenees": "122", 
    "Mastiff Spanish": "486", 
    "Appenzell Mountain Dog": "18", 
    "Shepherd": "212", 
    "Belgian Shepherd Tervuren": "34", 
    "White German Shepherd": "241", 
    "Boston Terrier": "50", 
    "Akita": "9", 
    "Pyrenean Shepherd": "456", 
    "Dachshund-Miniature ": "313", 
    "Pug": "191", 
    "Galgo Spanish Greyhound": "110", 
    "Pinscher-Miniature ": "161", 
    "GoldenDoodle": "535", 
    "Retriever, Labrador": "198", 
    "Kerry Blue Terrier": "144", 
    "Collie Rough": "465", 
    "Terrier Toy Manchester": "530", 
    "Doberman Pinscher": "85", 
    "Dalmatian": "83", 
    "Staffordshire Bull Terrier": "222", 
    "Newfoundland Dog": "165", 
    "Mastiff English": "485", 
    "English Springer Spaniel": "96", 
    "Redbone Coonhound": "195", 
    "Peekapoo": "538", 
    "Borzoi": "49", 
    "Picardy Shepherd": "180", 
    "Cockapoo": "75", 
    "Chesapeake Bay Retriever": "67", 
    "Bouvier Des Flanders": "51", 
    "Affenpinscher": "5", 
    "Mountain Cur": "162", 
    "Tibetan Mastiff": "227", 
    "Husky": "129", 
    "Terrier Parson Russell": "527", 
    "Norfolk Terrier": "166", 
    "Chiweenie": "38", 
    "Rat Terrier": "194", 
    "Border Collie": "46", 
    "Thai Ridgeback": "226", 
    "German Pinscher": "111", 
    "Pomeranian Toy": "494", 
    "Schnauzer Standard": "502", 
    "Polish Lowland Sheepdog": "186", 
    "Flat-Coated Retriever": "106", 
    "Black Russian Terrier": "40", 
    "Labrador Retriever": "149", 
    "Shar Pei": "210", 
    "Terrier English Bull": "526", 
    "Black And Tan Coonhound": "37", 
    "Lagotto Romagnolo": "482", 
    "Malinois": "484", 
    "Basset Hound": "24", 
    "Australian Terrier": "22", 
    "Briard": "54", 
    "Field Spaniel": "102", 
    "Pinscher": "490", 
    "Irish Terrier": "132", 
    "Keeshond": "143", 
    "Hound Swiss": "478", 
    "Finnish Lapphund": "104", 
    "Collie": "77", 
    "Siberian Husky": "216", 
    "Blue Heeler": "543", 
    "Sussex Spaniel": "223", 
    "Pomeranian Standard": "493", 
    "English Setter": "94", 
    "Sheepdog Iceland": "507", 
    "Airedale Terrier": "7", 
    "Kyi Leo": "148", 
    "Saluki": "203", 
    "Bichon Frise": "36", 
    "Saint Bernard": "202", 
    "Anatolian Shepherd": "17", 
    "Stumpy Tail Cattle Dog": "523", 
    "Kuvasz": "147", 
    "Cairn Terrier": "59", 
    "Shepherd Australian": "510", 
    "Spitz": "221", 
    "American Staffordshire Terrier": "15", 
    "Irish Wolfhound": "134", 
    "Foxhound": "108", 
    "Munsterland": "487", 
    "Shepherd Anatolian": "509", 
    "Pomeranian": "187", 
    "Toy Fox Terrier": "231", 
    "Bulldog": "462", 
    "Italian Greyhound": "135", 
    "Barbet": "458", 
    "Welsh Corgi Pembroke": "532", 
    "Maremma Sheepdog": "158", 
    "Spaniel": "220", 
    "Sheep Dog": "211", 
    "Boxer": "52", 
    "Spaniel French": "517", 
    "Sheepdog Dutch": "506", 
    "Mastiff": "159", 
    "Eskimo Dog": "99", 
    "German Shepherd/Purebred": "113", 
    "Petit Basset Griffon Vendeen": "178", 
    "Golden Retriever": "119", 
    "Catahoula Leopard Dog": "63", 
    "Italian Spinone": "136", 
    "Bloodhound": "41", 
    "German Spitz": "115", 
    "Greater Swiss Mountain Dog": "123", 
    "Gordon Setter": "120", 
    "Kishu": "145", 
    "Wolfhound Russian": "534", 
    "German Shepherd Dog": "112", 
    "Australian Kelpie": "20", 
    "Jindo Korean": "479", 
    "Sheepdog Tatra Mountain": "508", 
    "Terrier Sealyham": "528", 
    "Bergmasco": "459", 
    "Japanese Chin": "139", 
    "American Hairless Terrier": "14", 
    "Corgi": "79", 
    "Whippet Long Haired": "533", 
    "Harrier": "125", 
    "Groenendael": "476", 
    "Skye Terrier": "218", 
    "Weimaraner": "234", 
    "Rottweiler": "201", 
    "Chihuahua Long Haired": "463", 
    "Blue Lacy": "42", 
    "Chinese Shar-Pei": "70", 
    "German Shorthaired Pointer": "114", 
    "Old English Bulldog": "172", 
    "Shepherd Dutch": "512", 
    "Spaniel Blue Picardy": "516", 
    "Tibetan Terrier": "229", 
    "English Coonhound": "92", 
    "Rhodesian Ridgeback": "199", 
    "Boerboel": "44", 
    "Setter Llewellin": "504", 
    "Lhasa Apso": "154", 
    "Griffon": "475", 
    "Laeken": "481", 
    "Tibetan Spaniel": "228", 
    "Poodle Miniature": "541", 
    "Dachshund Long Haired": "467", 
    "Glen Of Imaal Terrier": "118", 
    "Bullmastiff": "58", 
    "Papillon": "174", 
    "Australian Cattle Dog": "19", 
    "Spaniel Picardy": "520", 
    "Plott Hound": "183", 
    "Portuguese Water Dog": "189", 
    "Australian Shepherd": "21", 
    "Pudelpointer": "498", 
    "Hovawart": "128", 
    "Beagle": "26", 
    "Mix": "3", 
    "Spaniel German": "518", 
    "Afghan Hound": "6", 
    "Akbash": "8", 
    "Pointer Braque D'Auverge": "491", 
    "Cirneco dell'Etna": "545", 
    "Shetland Sheepdog Sheltie": "213", 
    "Xolo/Mexican Hairless": "245", 
    "Pointer German": "492", 
    "Wire Fox Terrier": "242", 
    "Bernese Mountain Dog": "35", 
    "German Wirehaired Pointer": "116", 
    "Alaskan Malamute": "11", 
    "Dogue De Bordeaux": "87", 
    "Tosa Inu": "230", 
    "Brittany Spaniel": "55", 
    "Leonberger": "153", 
    "Eurasier": "471", 
    "French Bulldog": "109", 
    "Jack Russell Terrier (Parson Russell Terrier)": "138", 
    "Irish Water Spaniel": "133", 
    "Welsh Corgi Cardigan": "531", 
    "Bedlington Terrier": "30", 
    "Schnoodle": "539", 
    "English Bulldog": "90", 
    "Komondor": "480", 
    "Whippet": "240", 
    "English Shepherd": "95", 
    "Maltese": "156", 
    "Bearded Collie": "28", 
    "Chow Chow": "72", 
    "Mountain Dog": "163", 
    "Chihuahua Short Haired": "464", 
    "Foxhound American": "472", 
    "Belgian Shepherd": "31", 
    "Wheaten Terrier": "239", 
    "Feist": "101", 
    "Sarplaninac": "500", 
    "Carolina Dog": "62", 
    "Bull Terrier": "57", 
    "Fila Brasileiro": "103", 
    "Patterdale Terrier (Fell Terrier)": "175", 
    "Belgian Shepherd Laekenois": "32", 
    "Caucasian Sheepdog (Caucasian Ovtcharka)": "65", 
    "Great Dane": "121", 
    "Terrier Cesky": "525", 
    "Hound Hamilton": "477", 
    "Dutch Shepherd": "89", 
    "Spaniel American Cocker": "515", 
    "Norweigan Lundehund": "489", 
    "Jindo": "140", 
    "Poodle Toy": "496", 
    "Porter English": "497", 
    "Dachshund Standard": "468", 
    "Terrier Bull Miniature": "524", 
    "Pointer": "185", 
    "Welsh Corgi": "235", 
    "Maltipoo": "537", 
    "Ibizan Hound": "130", 
    "Pit Bull": "182", 
    "Cavalier King Charles Spaniel": "66", 
    "Pit Bull Terrier": "181", 
    "Old English Sheepdog": "171", 
    "Poodle Standard": "495", 
    "Queensland Heel": "499"
    },
    "cat": {
    "Others": "4",
    "Abyssinian": "248",
    "American Curl": "249",
    "American Shorthair": "250",
    "American Wirehair": "251",
    "Applehead Siamese": "252",
    "Balinese": "253",
    "Bengal": "254",
    "Birman": "255",
    "Bobtail": "256",
    "Bombay": "257",
    "British Shorthair": "258",
    "Burmese": "259",
    "Burmilla": "260",
    "Calico": "261",
    "Canadian Hairless": "262",
    "Chartreux": "263",
    "Chausie": "264",
    "Chinchilla": "265",
    "Cornish Rex": "266",
    "Cymric": "267",
    "Devon Rex": "268",
    "Dilute Calico": "269",
    "Dilute Tortoiseshell": "270",
    "Domestic Long Hair": "271",
    "Domestic Medium Hair": "272",
    "Domestic Short Hair": "273",
    "Egyptian Mau": "274",
    "Exotic Shorthair": "275",
    "Extra-Toes Cat (Hemingway Polydactyl)": "276",
    "Havana": "277",
    "Himalayan": "278",
    "Japanese Bobtail": "279",
    "Javanese": "280",
    "Korat": "281",
    "Laperm": "282",
    "Maine Coon": "283",
    "Maltese": "542",
    "Manx": "284",
    "Munchkin": "285",
    "Nebelung": "286",
    "Norwegian Forest Cat": "287",
    "Ocicat": "288",
    "Oriental Long Hair": "289",
    "Oriental Short Hair": "290",
    "Oriental Tabby": "291",
    "Persian": "292",
    "Pixie-Bob": "293",
    "Ragamuffin": "294",
    "Ragdoll": "295",
    "Russian Blue": "296",
    "Scottish Fold": "297",
    "Selkirk Rex": "298",
    "Siamese": "299",
    "Siberian": "300",
    "Singapura": "301",
    "Snowshoe": "302",
    "Somali": "303",
    "Sphynx (Hairless Cat)": "304",
    "Tabby": "305",
    "Tiger": "306",
    "Tonkinese": "307",
    "Torbie": "308",
    "Tortoiseshell": "309",
    "Turkish Angora": "310",
    "Turkish Van": "311",
    "Tuxedo": "312",
    }
}

HELP_PARAM = {
    "__EVENTTARGET": "gvOrgPets",
    "__EVENTARGUMENT": "Page$1",
    "__LASTFOCUS": "",
    "__VIEWSTATE": "IW2VjdI0L7WVOooG5rYN8xavcSAExAeSAhjbntmTGSZmSJBQdCiUxMWxVUUOSv93+emHXbKOFc2nnPQz0oCf8GCoI1Yv/7tFwR/jPPAlGLLUeUmVZ6YuP2Xd0QRDea91RgelG+bD/JZOo3L6H3mGfVw3S91WLqW8ZSaEFoLO8TROCvgYPdOsLk23GlI7Ls5+vGo/28UsLU41cCW7I7EDWPXIWs9RcDPrIIYF5RZCGlLxNygSOUCNeYYaGXiYp++M1Fb386crZ39ayXlmqJCUAtG1dBxEPjPD05MF9VAxFJc889BZnI0JeDTyuXYtewuz1QBNKVV8j3Vezz+AlTHFOgs6tUIwHI20qvp46SrSptiOkgPJRyOBdscCdirauU78nUMmeHzmE8JEj02wpPwZGAC7T5y6dFJ8JjO56/9OZMP0aWBwFGKGzaqHZD3Vf5vLxFafTlggH9jRTJ8G2z0953itT8FrIagb/WkF4S6eZpZUTyXLm3deASCLR5LxcgbsfAh/+g9uBTa275eMz1Muuxo/yZgeY8WB47ZqQjhMycRJtyeqBum186CqeGCr2v7ji4wHGPyLtyzKE3oX7K0uqlTHs6BvDSdfm0nLHL/C13zEuJ5QMIwRxN32GaIFibKbD4NswmSBK4y9BLwFWC1pSmngFTaDihicduAozc/XXmV5iIKm9JyK/y6x3oPrj3iipum45CBu07+mcXKCQHxXUHJ2e5UFp2JiPe4nw0ILaUv7tZDO1s1nSD7/55EOAHvjVkE+irxCXXYBYqlda6IeV6AOO1EJX3JdRE//lp7rwq6Xu5CLx6cJOudbrTdBquRrlgD1pI8IcfB6OA41Wrhhxuoj2/p6CjV86/0Xvp/daUHuaxfQ9mecfUwwhISJaPxNXUHPX3wNHD4Sf0T9TGIGXfb+u63CedG4+9KYNUn9f8lBlfBk8scu+XAt9viO8evcRY38tVbC1H2kR/XJNKepFbgTWwLtOpF3mhKYdAjg1L5jNt5BCMAB6XyOzwEQwjvlyVy97qHMPFanx7rpnxmICLmboXov0ir8a+iJu4fLumsbvZS5couqt0J2l9ClO9AgR/rhtET8I6SvomTbl5oFOvXMefgWJVcsNn+6k24e4xePXdqfuGw7Cuyvp9aRMBG8O9qPyuZKpKX8kLJN5xKC85HJnk8WwAyTW5VMt6TEEAEfxjHGrePKJRVNWluzoIRreRFeuL8MuJWHyCSGr72/Op4f5kCRforkGzyczc9RlPHcb8cIB0ZhXV90O90mcmnAZ+JiV+WJSAmXwN9epukk+/jWXBcIK9SvADl9tJJQb28bBn4b5Zi4YetMcJik1tJczUmdViVVyM3CLqerHl0oJ9oTHqJf6CulJbjq/GNxq4D227gt7UFeEiV8wjx6oWiaYr8E+NYBxBzVM0S8lEf4rmH4UkMB0BzxT7XVYAMLtFZTj+1/Ltdqtrl9KOPubeScggF9S8q636Nm/YnvMmTSkrWOrBM1PW1H75gjWEIM6eVPH+pG7pZogKjf/iL8QpGva+Ab78aSmq2FCZs4c3OGjpvkfJy+/WI9ziLrBotjLCvRLD2Bfn2OCb06DoQ4YiFH3yKX33cj+iQcoj4+wdnJcS6BrN5oaoGLHnc4oWEUWVMNk9Yz7nq8NUcLdBQZJe0MQleW9tTIVy73pWeNvI7bIZNSti46yrlU43MQghwVJxMXpRnC1D0K7oMgV30yB3cIT7uPfkBd8tt9sZ21fJ84J3ftWNKakTUUwzepbINxosdubPDUmeyrHBUXHjRkJI/f8qhAlDzSDKPW/tr3sSMUv//9laIviKtwvCHZPnimfEAbc9x4PI80XTAUP9W7q2cpjhIkSaJ1xLyeIAci/FLH913jU+U35Fizp3wtpc55Y+T4OKSJ4o1JJUDS7lrRVKuytgW4jMZsPPfxW644+uChVwajHPffKoZQht8nUXRpzT4ITslqJCRfL76PZThCOJjc5DqIYWAIHnR8banBeRkjYQU489bhNQYj9iEDYdm6l5TfFYu+XLHE/FvooMH+68pLAvP5+e7ZCEhd2PK4Y/rgY8C5AAI3h2J2FrOqs2znNvwpaUTvWVMBSVWIHRwOThTyR73mq6VBkzHlvBD+a0xS1z5zVlG7xcqujdjl7166bT2uzP05hcj0LoSjxg7ZggEhak6cYcPmV1fxRbYcf/KeLVSSNbNj7dlWS2q5/oLx95ylgbJUI/2Cgn1D9e0MQzkXxFumkr78AjsTXepqThKfkdHgq7pimCevBLCyXPlcZgP5ZC7cohMTsX5LRff0anghrnrAF977HB8/+2FE1LXUnRB9iwhDOrQl+VL/OwQQXAHtmQ5qluKJ/Db4jRpQrLv1WbLc25NGflUWKZPACvbE+tRZCr/YHInkS00yCLktWWCQiW/r0rCHmHsfYpc6RMWfiTNf0pClIthB36BlujSDPIycCmzM0KufdNsbfrP20Wz6kmthb8uHCRlooqp3DOlyvd7RC1RkdWkKJenmGqL9ES2syOiUtzaCVA5CoJBjHx1XxYo2ZodzYniGNl5gq8oKjrkflCiApwNjw8nWFD4tKfwkn271ud/M3KLZnygQgrTwJS8+an29oHQAWPqJliJBk4OQC2NHUEJWEuDTtqxrd1BEldoDS0Dvw3CHJoJD/wQaF//W5ul2L+wVUSPX2Hg58ScddsPwbwEwd1DhJDDkvmbF0d8K4f7dUEUzIhxkWJr3Vnn7XL2O0qLNDMCoPcwJVXUueFjNArrz+1hJZratn9ghHrsbSWsb2VllriDZFBAKLnoagh5WOwAKEfpHCP46YuFhCLeztLHlZ/uSjwcqoom3YkyMLL8MJx4prCuUP3RgU0E3/ZPKVIhV0HpK4K7woZfaRjLdc8kerzEedB5hlSxDDEHhAO+eZr6DTVuAevxDU/0NKr1cicS7viiwUrodr1WM7/el+Ji34o4KVxJXqamzbQQUqiAUNmvxhTt2zb7KM6jR73aypUBxSpewIlNLJNhGGJUd0+d3LH83I0j+bASBoK2fekDJ3mXcvTMOU90aB+McNNWyC0tWER8cQb7KbznkeUtfSFUQSS3Ues3p2MOyvQlshp5REQdFLQjtZ8X+kLpFP7PCL+/wdo11zpOjlHLmQqmVpePQuu9lahtLMeQDmsR2M7Su/L+hcu0aeRzdi7nJ3txehOj6pHgwb4rsu2r9Ykv73kuSnTgbytx23NAhBZvinCCPz+dOTx9wrD2JTj1yebGEGK7ZlggigH5djWTYhc+tJUt+AJTcgxeuH9mQ2FuwPzCAkOBoiDsHwe/lKsziKoVjKdlLIRrl1uyJ2Mop8336N7X1buv0T/uR52T+oXhTcKKkcOSdVUbYSARLeDOK1+Cyp476juM8m1ZhcS34YKiNj9JTEX3J4y8mX8Tn18qo/bP17f/+SRJrocqVdUQmu2CTsBnMoCH48l1iR8DxyE7TVQW1wlCBXjeI8V/r2SVst/4uu1A51cW70udgfmTdYg576qk7/0cqW9237XzkfIg1DJKmnytN2IZQ00tcGHm5RHOSkY910UHKT8lOMIORui4GsZRmBuqn6X/A38RCfl53bovk8DUkBoUDyXJ/l2GtA4omISugCwgTIwcKxOHPA7sh27WJcNUptanBUrZ/VW1uzU/pXi0CV34VtYcPUvzy7DSQUmI37Py+USkOnU0Lk9mGEi27rzGo9r2HPtA9MWku4K52fOF9rkojC7NaOp+1OTCp52+aa/0I9+rZy1FO8FzgWBt3FQ9JOdB6Jep1Han2a5j2CAZhG/y2Yy+tcZQ6LZhSMEaH8DhhASL16DlKegK3Vgo44Ol5Ax/P1jnruFAkG/PJDk9yRARNtMBOX2pGsVJ/V+5G2hPx4L3b1tdANHWInEaOYlygdeEDYBitiyy02kI93eDpXJWRWN0QhEZAHCH2bVXNhpy7NifLkh5cLMwc8VIeKPG40DJ2hdmfFzEVpMixK40lQNo3hiOrmCiV5cQQbyWrFtTd7eMmeNzI96D35mWncjOiLE8T4d9en3f3hzzyWHYuFJQVnoLUiXae0WBDUMcxcgHLz8vG1P/70Idaq0UjZrZrC1yDMk81eFQWryOvxstWbmEkqrHj68AWdgudH9vR2yoU1Una/PuaWjc3udO8wmkJvQaGFYb2f7ZfskdO3T9Nq7QUGA9KK5XqDxN/Kz1DUfauKBO11ivWAURCs7TeMKXc74FCZZFfbnP0TDPqUBEJ1pnZDOLRStoZprPTR2BUnmmi2f54QA6ULOq+nmjG6NQt/LeQMecQ2rFbfck6z5ye/W8KZ1Gady3W/qIiUcXaCnwwtfrx9Kj7rgjebEjkKi1SsXtLi8A3KPlcVG7O+yNhog7XDWLHBMzpHbzKVaYxHfZ1Cjk2+jhYMt5+jpwjPVEMAnn3ZB/RIlkwBRKfCS0OT4ncIdXeP2KqgpbeexthHHI858Xl3GhlPVisshfWB0oOrS39PJiWK2FueTo2PUumqgfqDra+kemsbAXgwFakOWANPpaTxTbLoRq6CbSZvZSH//4e1UN54sUCwIPxfoHxCY+dP4Dfe5pCFo6TwjO+tcpAkAfejqbslYv2vWuvSJsjrf4w5OKyqoUZI2YYXY59EK3Su4LwdCXDG792opDuAUrvJtu/lUx5XdJ2mpqSsplr6qdlAHn89IYhdRMZw7rYInArJ2fkJo1mehLFaR7Zzdqh2RHk3WE8Y48u5MiCXaaWbOXLs6mTW6Y0pIhz7wNEaSJebto7IayrKu2ldPQZlnl3RgBmP1UQLYtVCYeGJYdIekiPM7+jSjs6WXZAaZMVFwwIIgHNLk1hfV5XxaU6+JXHBqOGkFQ8fEznSYUlx5gjCZ9EA2ofAsUbLMsBLeJOE16LOhYIcvlavKY+TvK6ZxUm1MmkhjUL2yr/ZzF3J+YthzCj6DmRNoiFObA5a3fjzSm8uPqj7U1sUvd+3PVAYgbHzExKT8WHOsd7KOk6GBUsWZCkxEuu+OaSmcrwVnCjeWVS5AFyIlj2VeT8z8wvlPqvYq9z7tp6dWO34yNhvr+92Nm9fxELLEGjg9Pu348XUyTUX337IsKU6HaggrFhjtJff3EHmgCEeUxcJFHYjWXNEB0b1/AmKtl4H4vvX80ee7NlINZDLLcvLiCGnCgl+kxVTw0ljMNTUQ6ZbUZ0xnMX5ttq",
    "__VIEWSTATEGENERATOR": "EAEFC5A4",
    "__VIEWSTATEENCRYPTED": "",
    "hdnOrgID": "188",
    "hdnOrgServiceID": "28",
    "ddlStatus": "2",
    "txtStatusDate": "August 15, 2016",
    "ddlSpecies": "2",
    "ddlBreed1": "",
    # "ddlSizes": "2",
    "ddlGender": "Male",
    "ddlAges": "0",
    "txtColor": "",
    "ddlProvince":"- All -",
    "ddlCounty": "- All -",
    "ddlCity": "- All -",
    "ddlZip": "- All -",
    # "chkShow1Org": "on",
    "ddlRank": "statusdate",
    "CascadingDropDown_Species_ClientState": "2:::Dog:::",
    "CascadingDropDown_Breed1_ClientState": "::::::",
    "CascadingDropDown_Sizes_ClientState": "::::::",
    "hiddenInputToUpdateATBuffer_CommonToolkitScripts": "0",
}

HELP_SIZE = {
    "small": ["1", "1:::Small (Under 20 lbs):::"],
    "medium": ["2", "2:::Medium (21~45 lbs):::"],
    "large": ["3", "3:::Large (46~100 lbs):::"]
}

HELP_SPECIES = {
    "dog": ["2", "2:::Dog:::"],
    "cat": ["3", "3:::Cat:::"]
}

HELP_GENDER = {
    "boy": "Male",
    "girl": "Female"
}

HELP_MONTH = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "Jun",
    "07": "July",
    "08": "August",
    "09": "September",
    "10": "October",
    "11": "November",
    "12": "December"
}

PATHARBOR_PARAM = {
    "searchtype": "LOST",
    "stylesheet": "include/default.css",
    "frontdoor": "1",
    "friends": "1",
    "samaritans": "1",
    "nosuccess": "0",
    "rows": "10",
    "imght": "120",
    "imgres": "thumb",
    "tWidth": "200",
    "view": "sysadm.v_animal",
    "fontface": "arial",
    "fontsize": "10",
    "zip": "",
    "miles": "20",
    "shelterlist": "",
    "atype": "dog",
    "ADDR": "undefined",
    "grid": "0",
    "nav": "1",
    "start": "4",
    "nomax": "1",
    "page": "1",
    "where": ""
}

PATHARBOR_BREED = {
    "Pug": "TOY^PUG", 
    "English Pointer": "POINTER^ENG POINTER", 
    "Otterhound": "SHEEPDOG^OTTERHOUND", 
    "Norwegian Buhund": "SPITZ^NORW BUHUND", 
    "Clumber Spaniel": "SPANIEL^CLUMBER SPAN", 
    "Tibetan Terrier": "TERRIER^TIBETAN TERR", 
    "Basenji": "SIGHTHOUND^BASENJI", 
    "Black Mouth Cur": "HOUND^BLACK MOUTH CUR", 
    "Leonberger": "SETTER/RETRIEVE^LEONBERGER", 
    "English Toy Spaniel": "SPANIEL^ENG TOY SPANIEL", 
    "Chinese Crested Dog": "TOY^CHINESE CRESTED", 
    "Beauceron": "SETTER/RETRIEVE^BEAUCERON", 
    "Brussels Griffon": "TERRIER^BRUSS GRIFFON", 
    "Lhasa Apso": "TOY^LHASA APSO", 
    "Welsh Springer Spaniel": "SPANIEL^WELSH SPR SPAN", 
    "Schipperke": "TOY^SCHIPPERKE", 
    "Lowchen": "TOY^LOWCHEN", 
    "Irish Setter": "SETTER/RETRIEVE^IRISH SETTER", 
    "Cane Corso": "MASTIFF^CANE CORSO", 
    "Cocker Spaniel": "SPANIEL^COCKER SPAN", 
    "Scottish Deerhound": "SIGHTHOUND^SCOT DEERHOUND", 
    "Collie - Rough": "COLLIE^COLLIE ROUGH", 
    "American Pit Bull Terrier": "MASTIFF^AM PIT BULL TER", 
    "Others": "No Preference", 
    "Wire-haired Pointing Griffon": "POINTER^WH PT GRIFFON", 
    "Feist": "TERRIER^FEIST", 
    "Queensland Heeler": "COLLIE^QUEENSLAND HEEL", 
    "Havanese": "TOY^HAVANESE", 
    "Rhodesian Ridgeback": "HOUND^RHOD RIDGEBACK", 
    "Lakeland Terrier": "TERRIER^LAKELAND TERR", 
    "Spinone Italiano": "POINTER^SPINONE ITAL", 
    "Poodle - Standard": "POODLE^POODLE STND", 
    "English Cocker Spaniel": "SPANIEL^ENG COCKER SPAN", 
    "Neapolitan Mastiff": "MASTIFF^NEAPOLITAN MAST", 
    "Australian Cattle Dog": "COLLIE^AUST CATTLE DOG", 
    "Manchester Terrier": "TERRIER^MANCHESTER TERR", 
    "Yorkshire Terrier": "TOY^YORKSHIRE TERR", 
    "Brittany": "SPANIEL^BRITTANY", 
    "Pharaoh Hound": "SIGHTHOUND^PHARAOH HOUND", 
    "Swedish Vallhund": "SHEPHERD^SWED VALLHUND", 
    "Belgian Laekenois": "TERRIER^BELG LAEKENOIS", 
    "Dandie Dinmont Terrier": "TERRIER^DANDIE DINMONT", 
    "Korean Jindo": "SPITZ^JINDO", 
    "Alaskan Husky": "SPITZ^ALASKAN HUSKY", 
    "Catahoula Leopard Hound": "HOUND^CATAHOULA", 
    "Eurasier": "SPITZ^EURASIER", 
    "Bichon Frise": "POODLE^BICHON FRISE", 
    "Dogue de Bordeaux": "MASTIFF^DOGUE DE BORDX", 
    "Vizsla - Wirehaired": "POINTER^VIZSLA WH", 
    "Greyhound": "SIGHTHOUND^GREYHOUND", 
    "Swiss Hound": "HOUND^SWISS HOUND", 
    "Norwich Terrier": "TERRIER^NORWICH TERRIER", 
    "Patterdale Terrier": "TERRIER^PATTERDALE TERR", 
    "Shih Tzu": "TOY^SHIH TZU", 
    "Anatolian Shepherd": "MASTIFF^ANATOL SHEPHERD", 
    "Shiba Inu": "SPITZ^SHIBA INU", 
    "St Bernard - Smooth Coated": "MASTIFF^ST BERNARD SMTH", 
    "Airedale Terrier": "TERRIER^AIREDALE TERR", 
    "Pekingese": "TOY^PEKINGESE", 
    "Canaan Dog": "SPITZ^CANAAN DOG", 
    "Shetland Sheepdog": "COLLIE^SHETLD SHEEPDOG", 
    "Samoyed": "SPITZ^SAMOYED", 
    "Greater Swiss Mountain Dog": "SETTER/RETRIEVE^GR SWISS MTN", 
    "Belgian Malinois": "SHEPHERD^BELG MALINOIS", 
    "Landseer": "SETTER/RETRIEVE^LANDSEER", 
    "Old English Bulldog": "MASTIFF^OLD ENG BULLDOG", 
    "Great Pyrenees": "SETTER/RETRIEVE^GREAT PYRENEES", 
    "Schnauzer - Standard": "TERRIER^SCHNAUZER STAND", 
    "Carolina Dog": "SHEPHERD^CAROLINA DOG", 
    "Welsh Corgi - Pembroke": "SHEPHERD^WELSH CORGI PEM", 
    "Boston Terrier": "TOY^BOSTON TERRIER", 
    "Pit Bull Terrier": "MASTIFF^PIT BULL", 
    "American Staffordshire Terrier": "MASTIFF^AMERICAN STAFF", 
    "Cirneco dell Etna": "SIGHTHOUND^CIRNECO", 
    "Norwegian Elkhound": "SPITZ^NORW ELKHOUND", 
    "Finnish Spitz": "SPITZ^FINNISH SPITZ", 
    "Irish Terrier": "TERRIER^IRISH TERRIER", 
    "Dachshund - Longhaired": "TOY^DACHSHUND LH", 
    "Kerry Blue Terrier": "TERRIER^KERRY BLUE TERR", 
    "Fox Terrier - Smooth": "TERRIER^FOX TERR SMOOTH", 
    "Schnauzer - Miniature": "TERRIER^SCHNAUZER MIN", 
    "Doberman Pinscher": "POINTER^DOBERMAN PINSCH", 
    "Dalmatian": "POINTER^DALMATIAN", 
    "American Bulldog": "MASTIFF^AMER BULLDOG", 
    "Staffordshire Bull Terrier": "MASTIFF^STAFFORDSHIRE", 
    "Presa Canario": "MASTIFF^PRESA CANARIO", 
    "Pumi": "POODLE^PUMI", 
    "Bouvier des Flandres": "SHEEPDOG^BOUV FLANDRES", 
    "Redbone Coonhound": "HOUND^REDBONE HOUND", 
    "Puli": "SHEEPDOG^PULI", 
    "Boerboel": "MASTIFF^BOERBOEL", 
    "Borzoi": "SIGHTHOUND^BORZOI", 
    "Sealyham Terrier": "TERRIER^SEALYHAM TERR", 
    "Black and Tan Coonhound": "HOUND^BLACK/TAN HOUND", 
    "Chesapeake Bay Retriever": "SETTER/RETRIEVE^CHESA BAY RETR", 
    "Keeshond": "SPITZ^KEESHOND", 
    "Welsh Corgi - Cardigan": "SHEPHERD^WELSH CORGI CAR", 
    "Tibetan Mastiff": "MASTIFF^TIBETAN MASTIFF", 
    "Gordon Setter": "SETTER/RETRIEVE^GORDON SETTER", 
    "Norfolk Terrier": "TERRIER^NORFOLK TERRIER", 
    "Rat Terrier": "TERRIER^RAT TERRIER", 
    "Australian Shepherd": "COLLIE^AUST SHEPHERD", 
    "Border Collie": "COLLIE^BORDER COLLIE", 
    "German Pinscher": "POINTER^GERMAN PINSCHER", 
    "Curly-Coated Retriever": "POODLE^CURLYCOAT RETR", 
    "American Foxhound": "HOUND^AMER FOXHOUND", 
    "Dogo Argentino": "MASTIFF^DOGO ARGENTINO", 
    "Fox Terrier - Wirehaired": "TERRIER^FOX TERR WIRE", 
    "Schnauzer - Giant": "TERRIER^SCHNAUZER GIANT", 
    "Labrador Retriever": "SETTER/RETRIEVE^LABRADOR RETR", 
    "Chihuahua - Smooth Coated": "TOY^CHIHUAHUA SH", 
    "Mexican Hairless": "TOY^MEX HAIRLESS", 
    "Basset Hound": "HOUND^BASSET HOUND", 
    "Australian Terrier": "TERRIER^AUST TERRIER", 
    "Briard": "SHEEPDOG^BRIARD", 
    "Field Spaniel": "SPANIEL^FIELD SPANIEL", 
    "Pointer": "POINTER^POINTER", 
    "Dachshund": "TOY^DACHSHUND", 
    "Affenpinscher": "TERRIER^AFFENPINSCHER", 
    "Picardy Sheepdog": "TERRIER^PICARDY SHEEPDG", 
    "Siberian Husky": "SPITZ^SIBERIAN HUSKY", 
    "Sussex Spaniel": "SPANIEL^SUSSEX SPAN", 
    "Poodle - Toy": "POODLE^POODLE TOY", 
    "English Setter": "SETTER/RETRIEVE^ENG SETTER", 
    "Welsh Terrier": "TERRIER^WELSH TERRIER", 
    "Dachshund - Wirehaired": "TOY^DACHSHUND WH", 
    "Saluki": "SIGHTHOUND^SALUKI", 
    "Entlebucher Mountain Dog": "SETTER/RETRIEVE^ENTLEBUCHER", 
    "Kangal": "MASTIFF^KANGAL", 
    "Munsterlander": "SETTER/RETRIEVE^MUNSTERLANDER", 
    "Bluetick Coonhound": "HOUND^BLUETICK HOUND", 
    "Kuvasz": "SETTER/RETRIEVE^KUVASZ", 
    "Cairn Terrier": "TERRIER^CAIRN TERRIER", 
    "Vizsla": "POINTER^VIZSLA", 
    "Karelian Bear Dog": "SPITZ^KARELIAN BEAR", 
    "Irish Wolfhound": "SIGHTHOUND^IRISH WOLFHOUND", 
    "Weimaraner": "POINTER^WEIMARANER", 
    "Grand Basset Griffon Vendeen": "TERRIER^GBGV", 
    "Pomeranian": "TOY^POMERANIAN", 
    "Toy Fox Terrier": "TOY^TOY FOX TERRIER", 
    "Bulldog": "MASTIFF^BULLDOG", 
    "American Eskimo": "SPITZ^AMER ESKIMO", 
    "Parson (Jack) Russell Terrier": "TERRIER^PARSON RUSS TER", 
    "Italian Greyhound": "SIGHTHOUND^ITAL GREYHOUND", 
    "Newfoundland": "SETTER/RETRIEVE^NEWFOUNDLAND", 
    "Boxer": "MASTIFF^BOXER", 
    "Golden Retriever": "SETTER/RETRIEVE^GOLDEN RETR", 
    "Alaskan Klee Kai": "SPITZ^ALASK KLEE KAI", 
    "Treeing Cur": "HOUND^TREEING CUR", 
    "Petit Basset Griffon Vendeen": "TERRIER^PBGV", 
    "West Highland White Terrier": "TERRIER^WEST HIGHLAND", 
    "Chow Chow": "SPITZ^CHOW CHOW", 
    "Bloodhound": "HOUND^BLOODHOUND", 
    "English Shepherd": "COLLIE^ENG SHEPHERD", 
    "English Foxhound": "HOUND^ENG FOXHOUND", 
    "German Shepherd Dog": "SHEPHERD^GERM SHEPHERD", 
    "Australian Kelpie": "COLLIE^AUST KELPIE", 
    "Cavalier King Charles Spaniel": "SPANIEL^CAVALIER SPAN", 
    "Bearded Collie": "SHEEPDOG^BEARDED COLLIE", 
    "Whippet": "SIGHTHOUND^WHIPPET", 
    "Polish Lowland Sheepdog": "SHEEPDOG^POLISH LOWLAND", 
    "Harrier": "HOUND^HARRIER", 
    "Miniature Pinscher": "TERRIER^MIN PINSCHER", 
    "Skye Terrier": "TERRIER^SKYE TERRIER", 
    "Tennessee Treeing Brindle Hound": "HOUND^TENN TR BRINDLE", 
    "Poodle - Miniature": "POODLE^POODLE MIN", 
    "Flat-Coated Retriever": "SETTER/RETRIEVE^FLAT COAT RETR", 
    "German Shorthaired Pointer": "POINTER^GERM SH POINT", 
    "Jack (Parson) Russell Terrier": "TERRIER^JACK RUSS TERR", 
    "Akita": "SPITZ^AKITA", 
    "Fila Brasileiro": "MASTIFF^FILA", 
    "Afghan Hound": "SIGHTHOUND^AFGHAN HOUND", 
    "Collie - Smooth": "COLLIE^COLLIE SMOOTH", 
    "Nova Scotia Duck-Tolling Retriever": "SETTER/RETRIEVE^NS DUCK TOLLING", 
    "Coton de Tulear": "POODLE^COTON DE TULEAR", 
    "Tibetan Spaniel": "SPANIEL^TIBETAN SPAN", 
    "Rottweiler": "MASTIFF^ROTTWEILER", 
    "English Springer Spaniel": "SPANIEL^ENG SPRNGR SPAN", 
    "Chihuahua - Long Haired": "TOY^CHIHUAHUA LH", 
    "Bullmastiff": "MASTIFF^BULLMASTIFF", 
    "Papillon": "TOY^PAPILLON", 
    "Belgian Sheepdog": "COLLIE^BELG SHEEPDOG", 
    "Plott Hound": "HOUND^PLOTT HOUND", 
    "Portuguese Water Dog": "POODLE^PORT WATER DOG", 
    "Spanish Water Dog": "SHEEPDOG^SPAN WATER DOG", 
    "Hovawart": "SETTER/RETRIEVE^HOVAWART", 
    "Beagle": "HOUND^BEAGLE", 
    "Maremma Sheepdog": "SETTER/RETRIEVE^MAREMMA SHEEPDG", 
    "American Water Spaniel": "POODLE^AMER WATER SPAN", 
    "Akbash": "SETTER/RETRIEVE^AKBASH", 
    "English Coonhound (Redtick Coonhound)": "HOUND^ENG COONHOUND", 
    "Bernese Mountain Dog": "SETTER/RETRIEVE^BERNESE MTN DOG", 
    "German Wirehaired Pointer": "POINTER^GERM WH POINT", 
    "Alaskan Malamute": "SPITZ^ALASK MALAMUTE", 
    "Spanish Mastiff": "MASTIFF^SPANISH MASTIFF", 
    "Glen of Imaal Terrier": "TERRIER^GLEN OF IMAAL", 
    "Scottish Terrier": "TERRIER^SCOT TERRIER", 
    "French Bulldog": "MASTIFF^FRENCH BULLDOG", 
    "Irish Water Spaniel": "POODLE^IRISH WATR SPAN", 
    "English Bulldog": "MASTIFF^ENG BULLDOG", 
    "Komondor": "SHEEPDOG^KOMONDOR", 
    "Border Terrier": "TERRIER^BORDER TERRIER", 
    "Maltese": "TOY^MALTESE", 
    "Dutch Sheepdog": "SHEEPDOG^DUTCH SHEEPDOG", 
    "Silky Terrier": "TERRIER^SILKY TERRIER", 
    "Podengo Portugueso Pequeno": "TOY^PODENGO PEQUENO", 
    "Mastiff": "MASTIFF^MASTIFF", 
    "Bull Terrier": "TERRIER^BULL TERRIER", 
    "Boykin Spaniel": "SPANIEL^BOYKIN SPAN", 
    "Great Dane": "MASTIFF^GREAT DANE", 
    "Dutch Shepherd": "SHEPHERD^DUTCH SHEPHERD", 
    "Bernese Hound": "HOUND^BERNESE HOUND", 
    "Chinese Sharpei": "MASTIFF^CHINESE SHARPEI", 
    "Bedlington Terrier": "POODLE^BEDLINGTON TERR", 
    "Japanese Chin": "TOY^JAPANESE CHIN", 
    "Blue Lacy": "HOUND^BLUE LACY", 
    "Bull Terrier - Miniature": "TERRIER^BULL TERR MIN", 
    "Ibizan Hound": "SIGHTHOUND^IBIZAN HOUND", 
    "St Bernard - Rough Coated": "MASTIFF^ST BERNARD RGH", 
    "Treeing Walker Coonhound": "HOUND^TR WALKER HOUND", 
    "Belgian Tervuren": "COLLIE^BELG TERVUREN", 
    "Soft-Coated Wheaten Terrier": "TERRIER^SC WHEAT TERR", 
    "Old English Sheepdog": "SHEEPDOG^OLDENG SHEEPDOG", 
    "Tosa": "MASTIFF^TOSA"
}
